os: osx
language: node_js
node_js: 10

before_install:
  - brew install wine
install:
  - npm install -g yarn

before_script:
  - yarn

script:
  - yarn build
  - yarn dist:mac
  - yarn dist:win
  - yarn dist:linux
